=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/businessrules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Matthew Lourie (Home) -->
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by rp (vlct) -->
<!--W3C Schema generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<xs:schema elementFormDefault="qualified" version="1.0" id="brules" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="action">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="external-agent"/>
				<xs:element ref="inprocess-agent"/>
			</xs:choice>
			<xs:attribute name="Order" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="no"/>
						<xs:enumeration value="yes"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="argument" type="xs:string"/>
	<xs:element name="arguments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="argument" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute" type="xs:string"/>
	<xs:element name="commandline" type="xs:string"/>
	<xs:element name="comparator">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="equal"/>
						<xs:enumeration value="not-equal"/>
						<xs:enumeration value="equal-ignore-case"/>
						<xs:enumeration value="match"/>
						<xs:enumeration value="contain"/>
						<xs:enumeration value="less-than"/>
						<xs:enumeration value="less-than-or-equal"/>
						<xs:enumeration value="greater-than"/>
						<xs:enumeration value="greater-than-or-equal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="condition">
		<xs:complexType>
			<xs:choice>
				<xs:group ref="terms"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="expression">
		<xs:complexType>
			<xs:group ref="terms"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="external-agent">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="commandline"/>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer"/>
			<xs:attribute name="executeafter" type="idRef"/>
			<xs:attribute name="streamaccess" type="streamType"/>
			<xs:attribute name="wait" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="inprocess-agent">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer"/>
			<xs:attribute name="executeafter" type="idRef"/>
			<xs:attribute name="streamaccess" type="streamType"/>
			<xs:attribute name="class" type="xs:string"/>
			<xs:attribute name="wait" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute"/>
				<xs:element ref="comparator"/>
				<xs:element ref="value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="not">
	    <xs:complexType>
	    	<xs:group ref="terms"/>
	    </xs:complexType>
	</xs:element>
	<xs:element name="operator">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="and"/>
						<xs:enumeration value="or"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="param">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param-name"/>
				<xs:element ref="param-value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="param-name" type="xs:string"/>
	<xs:element name="param-value" type="xs:string"/>
	<xs:element name="params">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="condition"/>
				<xs:element ref="action"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="action"/>
						<xs:enumeration value="session"/>
						<xs:enumeration value="static"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="precedence" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="brpackage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rule" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="version" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="value" type="xs:string"/>

	<xs:group name="terms">
		<xs:sequence>
			<xs:choice>
			    <xs:element ref="not"/>
				<xs:element ref="item"/>
				<xs:element ref="expression"/>
				<xs:element ref="function"/>
			</xs:choice>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="operator"/>
				<xs:choice>
				    <xs:element ref="not"/>
					<xs:element ref="item"/>
					<xs:element ref="expression"/>
					<xs:element ref="function"/>
				</xs:choice>
			</xs:sequence>
		</xs:sequence>
	</xs:group>

	<xs:simpleType name="ynType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="no"/>
			<xs:enumeration value="yes"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="streamType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="all"/>
			<xs:enumeration value=""/>
			<xs:enumeration value="yes"/>
			<xs:enumeration value="none"/>
			<xs:enumeration value="output"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="idRef">
		<xs:union memberTypes="xs:integer">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
</xs:schema>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/MobileEnrollment.xml
<?xml version="1.0" encoding="UTF-8"?>
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="MobileEnrollment.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    <rule name="EnrollAccount" type="static" precedence="99">
        <condition>
            <item>
                <attribute>EventType</attribute>
                    <comparator name="equal" />
                <value>Application - PackagePostCommit</value>
            </item>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.axway.st.server.tm.packagemanager.agent.MobilePreEnrollmentAgent"/>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence" />
            <inprocess-agent id="3" executeafter="2" streamaccess="none" wait="yes" class="com.axway.st.server.tm.packagemanager.agent.MobilePostEnrollmentAgent"/>
        </action>
    </rule>
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/SendToSite.xml
<?xml version="1.0" encoding="UTF-8"?>
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd" name="SendToSite.xml">
    <rule name="SendToSite" type="static" precedence="99">
        <condition>
            <item>
                <attribute>EventType</attribute>
                <comparator name="equal" />
                <value>Incoming end</value>
            </item>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
            <inprocess-agent id="2" executeafter="1" streamaccess="all" wait="yes" class="com.tumbleweed.st.server.tm.agents.SendToSiteAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <param-name>Site</param-name>
                        <param-value></param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/InPermissionsCheck.xml
<?xml version="1.0" encoding="UTF-8"?>
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd" name="InPermissionsCheck.xml">

    <!-- In-Process Permissions Check Rules -->
    <rule name="InPermissionsCheck" type="static" precedence="22">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Incoming start</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Outgoing start</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - LIST</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - NLST</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - DELE</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - SIZE</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - RTCK</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - MDTM</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - CWD</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - MKD</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - RMD</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - RNFR</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FTP Cmd - RNTO</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FileMetadata - read</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>FileMetadata - update</value>
                </item>                   
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes"
                class="com.tumbleweed.st.server.tm.agents.PermissionsCheckAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes"
                class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>

</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/LogEntryMaintApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: LogEntryMaintApp.xml,v 1.1.2.3 2009-01-30 15:43:25 bzhivkov Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="LogEntryMaintApp.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
	<rule name="LogEntry Maintenance Application" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Application - Schedule</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_APPLICATION_TYPE</attribute>
                    <comparator name="equal" />
                    <value>LogEntryMaint</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.logentrymaintapp.agents.LogEntryMaintAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <param-name>deleteChunk</param-name>
                        <param-value>0</param-value>
                    </param>
                    <param>
                        <param-name>sleepBetweenChunkMillis</param-name>
                        <param-value>0</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/STAS2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: STAS2.xml,v 1.22.8.1 2009-11-03 11:27:33 apetrova Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="STAS2.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    
    <rule name="Post" type="static" precedence="100">
        
        <condition>
            <item>
                <attribute>EventType</attribute>
                <comparator name="equal" />
                <value>HTTP Cmd - POST</value>
            </item>
        </condition>
        
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="all" wait="yes" class="com.tumbleweed.st.server.as2.agent.AS2Agent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>

    <rule name="MDNPost" type="static" precedence="99">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>HTTP Cmd - POST</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_EXTRAARGS</attribute>
                    <comparator name="contain" />
                    <value>/mdn</value>
                </item>
            </expression>
        </condition>
    
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="all" wait="yes" class="com.tumbleweed.st.server.as2.agent.AS2MDNAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>

    <rule name="AS2Transfer" type="static" precedence="100">
        <condition>
            <expression>
                <expression>
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Server Transfer - Push</value>
                    </item>
                </expression>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="equal" />
                    <value>as2</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" class="com.tumbleweed.st.server.as2.agent.AS2TransferAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.RetryAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <param-name>dontretry</param-name><param-value>"0 1 2 4 5"</param-value>
                    </param>
                    <param>
                        <param-name>internalretry</param-name><param-value>"6"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>

    <rule name="AS2MDNTransfer" type="static" precedence="100">
        <condition>
            <expression>
                <expression>
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Server Transfer - Push</value>
                    </item>
                </expression>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="equal" />
                    <value>as2mdn</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" class="com.tumbleweed.st.server.as2.agent.AS2MDNTransferAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.RetryAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <param-name>dontretry</param-name><param-value>"0 1 2 4 5"</param-value>
                    </param>
                    <param>
                        <param-name>internalretry</param-name><param-value>"6"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>
    <rule name="AS2SessionCleanup" type="static" precedence="98">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>HTTP Cmd - POST</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_CLIENT</attribute>
                    <comparator name="equal" />
                    <value>as2d</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.NextPrecedence" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.CleanupAgent" />
        </action>
    </rule>
    
    <rule name="AccountReslvAS2" type="static" precedence="40">
        <condition>
        	<expression>
        		<item>
	                <attribute>DXAGENT_CLIENT</attribute>
	                <comparator name="equal"/>
	                <value>as2</value>
	            </item>
	        </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="all" wait="yes" class="com.tumbleweed.st.server.tm.agents.AccountResolveAgent" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>
        
</brpackage>
