=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/businessrules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Matthew Lourie (Home) -->
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by rp (vlct) -->
<!--W3C Schema generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<xs:schema elementFormDefault="qualified" version="1.0" id="brules" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="action">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="external-agent"/>
				<xs:element ref="inprocess-agent"/>
			</xs:choice>
			<xs:attribute name="Order" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="no"/>
						<xs:enumeration value="yes"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="argument" type="xs:string"/>
	<xs:element name="arguments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="argument" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute" type="xs:string"/>
	<xs:element name="commandline" type="xs:string"/>
	<xs:element name="comparator">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="equal"/>
						<xs:enumeration value="not-equal"/>
						<xs:enumeration value="equal-ignore-case"/>
						<xs:enumeration value="match"/>
						<xs:enumeration value="contain"/>
						<xs:enumeration value="less-than"/>
						<xs:enumeration value="less-than-or-equal"/>
						<xs:enumeration value="greater-than"/>
						<xs:enumeration value="greater-than-or-equal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="condition">
		<xs:complexType>
			<xs:choice>
				<xs:group ref="terms"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="expression">
		<xs:complexType>
			<xs:group ref="terms"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="external-agent">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="commandline"/>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer"/>
			<xs:attribute name="executeafter" type="idRef"/>
			<xs:attribute name="streamaccess" type="streamType"/>
			<xs:attribute name="wait" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="inprocess-agent">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer"/>
			<xs:attribute name="executeafter" type="idRef"/>
			<xs:attribute name="streamaccess" type="streamType"/>
			<xs:attribute name="class" type="xs:string"/>
			<xs:attribute name="wait" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute"/>
				<xs:element ref="comparator"/>
				<xs:element ref="value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="not">
	    <xs:complexType>
	    	<xs:group ref="terms"/>
	    </xs:complexType>
	</xs:element>
	<xs:element name="operator">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="and"/>
						<xs:enumeration value="or"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="param">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param-name"/>
				<xs:element ref="param-value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="param-name" type="xs:string"/>
	<xs:element name="param-value" type="xs:string"/>
	<xs:element name="params">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="condition"/>
				<xs:element ref="action"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="action"/>
						<xs:enumeration value="session"/>
						<xs:enumeration value="static"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="precedence" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="brpackage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rule" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="version" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="value" type="xs:string"/>

	<xs:group name="terms">
		<xs:sequence>
			<xs:choice>
			    <xs:element ref="not"/>
				<xs:element ref="item"/>
				<xs:element ref="expression"/>
				<xs:element ref="function"/>
			</xs:choice>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="operator"/>
				<xs:choice>
				    <xs:element ref="not"/>
					<xs:element ref="item"/>
					<xs:element ref="expression"/>
					<xs:element ref="function"/>
				</xs:choice>
			</xs:sequence>
		</xs:sequence>
	</xs:group>

	<xs:simpleType name="ynType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="no"/>
			<xs:enumeration value="yes"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="streamType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="all"/>
			<xs:enumeration value=""/>
			<xs:enumeration value="yes"/>
			<xs:enumeration value="none"/>
			<xs:enumeration value="output"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="idRef">
		<xs:union memberTypes="xs:integer">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
</xs:schema>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/ArchiveAgent.xml
<?xml version="1.0" encoding="UTF-8"?>
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="ArchiveAgent.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    <rule name="ArchiveMaint" type="static" precedence="29">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Incoming end</value>
                </item>
                <operator name="or" />
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Server Transfer - Push</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" class="com.tumbleweed.st.server.archivemaintapp.agents.ArchiveAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.NextPrecedence" />
        </action>
    </rule>
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/CustomTransfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: HttpTransfer.xml,v 1.8 2006-07-28 00:07:02 ygoulishev Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="CustomTransfer.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    <rule name="CustomTransfer" type="static" precedence="100">
        <condition>
            <expression>
                <expression>
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Server Transfer - Pull</value>
                    </item>
                    <operator name="or" />
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Server Transfer - Push</value>
                    </item>
                </expression>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>ftp</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>adhoc</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>http</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>ssh</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>pesit</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>folder</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>cd</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>synchrony transfer</value>
                </item>
                <operator name="and" />
                <not>
                    <item>
                        <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                        <comparator name="match" />
                        <value>mbft.*</value>
                    </item>
                </not>
                <operator name="and" />
                <not>
                    <item>
                        <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                        <comparator name="match" />
                        <value>as2.*</value>
                    </item>
                </not>
                <operator name="and" />
                <not>
                    <item>
                        <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                        <comparator name="match" />
                        <value>adhoc</value>
                    </item>
                </not>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" class="com.axway.st.server.plugins.site.agent.CustomTransferAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.RetryAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <!-- the event exit code for which the retry agent should flag a retry to the event queue -->
                        <param-name>dontretry</param-name><param-value>"0 1 2 4 5"</param-value>
                    </param>
                    <param>
                        <param-name>internalretry</param-name><param-value>"6"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="3" executeafter="2" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.Continue">
                <params>
                    <param>
                        <param-name>continue</param-name>
                        <param-value>"0 1 2 4 5"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>

</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/MDNReceipting.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: MDNReceipting.xml,v 1.12.4.1 2009-05-27 10:41:54 adzhigar Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="MDNReceipting.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">


<rule name="MDNPreReceipts" type="static" precedence="7">
        <condition>
            <expression>
                <expression>
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Incoming end</value>
                    </item>
                    <operator name="or" />
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Outgoing end</value>
                    </item>
                </expression>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_CLIENT</attribute>
                    <comparator name="not-equal" />
                    <value>as2</value>
                </item>
                <operator name="and" />
                <not>
                    <item>
                        <attribute>DXAGENT_PROTOCOL</attribute>
                        <comparator name="equal" />
                        <value>ftp-comb</value>
                    </item>
                    <operator name="and" />
                    <item>
                        <attribute>DXAGENT_TARGET</attribute>
                        <comparator name="match" />
                        <value>.*\.tmp</value>
                    </item>
                </not>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>adhoc</value>
                </item>
                <operator name="and" />
                <not>
                    <item>
                        <attribute>DXAGENT_API_CALL</attribute>
                        <comparator name="match"/>
                        <value>ADHOC_PACKAGE_.*</value>
                    </item>
                </not>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.VirtualPathMappingAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.CalcAttrsAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <param-name>NOASCII</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="3" executeafter="2" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.NextPrecedence" />
        </action>
</rule>

<rule name="MDNReceipts" type="static" precedence="27">
        <condition>
            <expression>
                <expression>
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Incoming end</value>
                    </item>
                    <operator name="or" />
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Outgoing end</value>
                    </item>
                </expression>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_CLIENT</attribute>
                    <comparator name="not-equal" />
                    <value>as2</value>
                </item>
                <operator name="and" />
                <not>
                    <item>
                        <attribute>DXAGENT_PROTOCOL</attribute>
                        <comparator name="equal" />
                        <value>ftp-comb</value>
                    </item>
                    <operator name="and" />
                    <item>
                        <attribute>DXAGENT_TARGET</attribute>
                        <comparator name="match" />
                        <value>.*\.tmp</value>
                    </item>
                </not>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_PROTOCOL</attribute>
                    <comparator name="not-equal" />
                    <value>adhoc</value>
                </item>
                <operator name="and" />
                <not>
                    <item>
                        <attribute>DXAGENT_API_CALL</attribute>
                        <comparator name="match"/>
                        <value>ADHOC_PACKAGE_.*</value>
                    </item>
                </not>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_FILE_STATUS</attribute>
                    <comparator name="not-equal" />
                    <value>8</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" class="mdn.MDNAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <param-name>SIGNING_ALIAS</param-name>
                        <param-value>mdn</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.NextPrecedence" />
        </action>
</rule>

</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/ServiceMaintenance.xml
<?xml version="1.0" encoding="UTF-8"?>
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd" name="ServiceMaintenance.xml">
    <rule name="ServiceBounce" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                   <attribute>EventType</attribute>
                   <comparator name="equal" />
                   <value>ServiceMaintenance - bounce</value>
               </item>
           </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.BounceRuleEngineAgent" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>
    <rule name="ServiceSyncStart" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                   <attribute>EventType</attribute>
                   <comparator name="equal" />
                   <value>ServiceMaintenance - syncstart</value>
               </item>
           </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.SyncStartAgent" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>
    <rule name="ServiceSyncEnd" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                   <attribute>EventType</attribute>
                   <comparator name="equal" />
                   <value>ServiceMaintenance - syncend</value>
               </item>
           </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.SyncEndAgent" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/AddressBookManager.xml
<?xml version="1.0" encoding="UTF-8"?>
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd" name="AddressBookManager.xml">  
   <rule name="AddressBookRetrieve" type="static" precedence = "50">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>AddressBook - retrieveentry</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.axway.st.server.addressbook.agents.AddressBookEntryRetrieveAgent" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>
    <rule name="AddressBookCount" type="static" precedence = "50">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>AddressBook - countentries</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.axway.st.server.addressbook.agents.AddressBookEntryCountAgent" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>
    <rule name="AddressBookSettings" type="static" precedence = "50">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>AddressBook - settings</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.axway.st.server.addressbook.agents.AddressBookSettingsAgent" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>
    <rule name="AddressBookValidate" type="static" precedence = "50">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>AddressBook - validate</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.axway.st.server.addressbook.agents.AddressBookValidateAgent" />
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence"/>
        </action>
    </rule>
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/AccountMaintenanceApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="AccountMaintenanceApp.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
	<rule name="Account Application" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Application - Schedule</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_APPLICATION_TYPE</attribute>
                    <comparator name="equal" />
                    <value>AccountTTL</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.axway.st.server.accountretentionapp.agents.AccountMaintenanceAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>
</brpackage>
