=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/businessrules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Matthew Lourie (Home) -->
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by rp (vlct) -->
<!--W3C Schema generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<xs:schema elementFormDefault="qualified" version="1.0" id="brules" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="action">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="external-agent"/>
				<xs:element ref="inprocess-agent"/>
			</xs:choice>
			<xs:attribute name="Order" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="no"/>
						<xs:enumeration value="yes"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="argument" type="xs:string"/>
	<xs:element name="arguments">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="argument" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="attribute" type="xs:string"/>
	<xs:element name="commandline" type="xs:string"/>
	<xs:element name="comparator">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="equal"/>
						<xs:enumeration value="not-equal"/>
						<xs:enumeration value="equal-ignore-case"/>
						<xs:enumeration value="match"/>
						<xs:enumeration value="contain"/>
						<xs:enumeration value="less-than"/>
						<xs:enumeration value="less-than-or-equal"/>
						<xs:enumeration value="greater-than"/>
						<xs:enumeration value="greater-than-or-equal"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="condition">
		<xs:complexType>
			<xs:choice>
				<xs:group ref="terms"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="expression">
		<xs:complexType>
			<xs:group ref="terms"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="external-agent">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="commandline"/>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer"/>
			<xs:attribute name="executeafter" type="idRef"/>
			<xs:attribute name="streamaccess" type="streamType"/>
			<xs:attribute name="wait" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="function">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="inprocess-agent">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:integer"/>
			<xs:attribute name="executeafter" type="idRef"/>
			<xs:attribute name="streamaccess" type="streamType"/>
			<xs:attribute name="class" type="xs:string"/>
			<xs:attribute name="wait" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="attribute"/>
				<xs:element ref="comparator"/>
				<xs:element ref="value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="not">
	    <xs:complexType>
	    	<xs:group ref="terms"/>
	    </xs:complexType>
	</xs:element>
	<xs:element name="operator">
		<xs:complexType>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="and"/>
						<xs:enumeration value="or"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="param">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param-name"/>
				<xs:element ref="param-value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="param-name" type="xs:string"/>
	<xs:element name="param-value" type="xs:string"/>
	<xs:element name="params">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="condition"/>
				<xs:element ref="action"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="action"/>
						<xs:enumeration value="session"/>
						<xs:enumeration value="static"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="precedence" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="brpackage">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="rule" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="version" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="value" type="xs:string"/>

	<xs:group name="terms">
		<xs:sequence>
			<xs:choice>
			    <xs:element ref="not"/>
				<xs:element ref="item"/>
				<xs:element ref="expression"/>
				<xs:element ref="function"/>
			</xs:choice>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="operator"/>
				<xs:choice>
				    <xs:element ref="not"/>
					<xs:element ref="item"/>
					<xs:element ref="expression"/>
					<xs:element ref="function"/>
				</xs:choice>
			</xs:sequence>
		</xs:sequence>
	</xs:group>

	<xs:simpleType name="ynType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="no"/>
			<xs:enumeration value="yes"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="streamType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="all"/>
			<xs:enumeration value=""/>
			<xs:enumeration value="yes"/>
			<xs:enumeration value="none"/>
			<xs:enumeration value="output"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="idRef">
		<xs:union memberTypes="xs:integer">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="0"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
</xs:schema>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/FolderTransfer.xml
<?xml version="1.0" encoding="UTF-8"?><!-- @(#) $Id: FolderTransfer.xml,v 1.8 2006-07-28 00:07:01 ygoulishev Exp $ --><!-- Do not delete the SecureTransport VERSION line below. --><!-- ~VERSION~ 1 --><brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="FolderTransfer.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    
    <rule name="FolderTransfer" precedence="100" type="static">
        
        <condition>
            
            <expression>
                
                <expression>
                    
                    <item>
                        
                        <attribute>EventType</attribute>
                        
                        <comparator name="equal"/>
                        
                        <value>Server Transfer - Pull</value>
                        
                    </item>
                    
                    <operator name="or"/>
                    
                    <item>
                        
                        <attribute>EventType</attribute>
                        
                        <comparator name="equal"/>
                        
                        <value>Server Transfer - Push</value>
                        
                    </item>
                    
                    <operator name="or"/>
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal"/>
                        <value>Server Transfer - Testlist</value>
                    </item>
                </expression>
                
                <operator name="and"/>
                
                <item>
                    
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    
                    <comparator name="equal"/>
                    
                    <value>folder</value>
                    
                </item>
                
                <operator name="and"/>
                
                <item>
                    
                    <attribute>DXAGENT_SITE_ATTR_REST_FOLDER_TRAVERSE</attribute>
                    
                    <comparator name="not-equal"/>
                    
                    <value>1</value>
                    
                </item>
                
            </expression>
            
        </condition>
        
        <action Order="yes">
            
            <inprocess-agent class="com.tumbleweed.st.server.folder.agent.FolderTransferAgent" executeafter="" id="1" streamaccess="none">
                
                <params>
                    
                    <param>
                        
                        <param-name>Impersonation</param-name>
                        
                        <param-value>"true"</param-value>
                        
                    </param>
                    
                </params>
                
            </inprocess-agent>
            
            <inprocess-agent class="com.tumbleweed.st.server.tm.agents.RetryAgent" executeafter="1" id="2" streamaccess="none">
                
                <params>
                    
                    <param>
                        
                        <param-name>Impersonation</param-name>
                        
                        <param-value>"true"</param-value>
                        
                    </param>
                    
                    <param>
                        <!-- the event exit code for which the retry agent should flag a retry to the event queue -->
                        
                        <param-name>dontretry</param-name>
                        
                        <param-value>"0 1 2 3 4 5"</param-value>
                        
                    </param>
                    
                    <param>
                        
                        <param-name>internalretry</param-name>
                        
                        <param-value>"6"</param-value>
                        
                    </param>
                    
                </params>
                
            </inprocess-agent>
            
            <inprocess-agent class="com.tumbleweed.st.server.tm.agents.Continue" executeafter="2" id="3" streamaccess="none">
                
                <params>
                    
                    <param>
                        
                        <param-name>continue</param-name>
                        
                        <param-value>"0 1 2 4 5"</param-value>
                        
                    </param>
                    
                </params>
                
            </inprocess-agent>
            
        </action>
        
    </rule>
    
    <rule name="FolderTraverse" precedence="99" type="static">
        
        <condition>
            
            <expression>
                
                <item>
                    
                    <attribute>EventType</attribute>
                    
                    <comparator name="equal"/>
                    
                    <value>Server Transfer - Pull</value>
                    
                </item>
                
                <operator name="and"/>
                
                <item>
                    
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    
                    <comparator name="equal"/>
                    
                    <value>folder</value>
                    
                </item>
                
                <operator name="and"/>
                
                <expression>
                    
                    <item>
                        
                        <attribute>DXAGENT_SUBSCRIPTION_ATTR_SCHEDULEDFOLDERMONITOR</attribute>
                        
                        <comparator name="equal"/>
                        
                        <value>1</value>
                        
                    </item>
                    
                    <operator name="or"/>
                    
                    <item>
                        
                        <attribute>DXAGENT_SITE_ATTR_REST_FOLDER_TRAVERSE</attribute>
                        
                        <comparator name="equal"/>
                        
                        <value>1</value>
                        
                    </item>
                    
                    <operator name="or"/>
                    
                    <item>
                        
                        <attribute>DXAGENT_API_CALL</attribute>
                        
                        <comparator name="match"/>
                        
                        <value>TransferPull.*</value>
                        
                    </item>
                    
                </expression>
                
            </expression>
            
        </condition>
        
        <action Order="yes">
            
            <inprocess-agent class="com.tumbleweed.st.server.folder.agent.FolderTraverseAgent" executeafter="" id="1" streamaccess="none">
                
                <params>
                    
                    <param>
                        
                        <param-name>Impersonation</param-name>
                        
                        <param-value>"true"</param-value>
                        
                    </param>
                    
                </params>
                
            </inprocess-agent>
            
        </action>
        
    </rule>
    
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/UnlicensedAccountMaintApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: ArchiveMaintApp.xml,v 1.1.2.1 2008-09-01 15:56:43 kmilchev Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="UnlicensedAccountMaintApp.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    <rule name="Unlicensed Account Maintenance Application" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Application - Schedule</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_APPLICATION_TYPE</attribute>
                    <comparator name="equal" />
                    <value>UnlicensedAccountMaint</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.axway.st.server.unlicensedmaintapp.agents.UnlicensedAccountMaintAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/ConnectDirectTransfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: ConnectDirectTransfer.xml,v 1.1.2.1 2008-08-04 10:54:15 mmincheva Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="ConnectDirectTransfer.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    <rule name="ConnectDirectTransfer" type="static" precedence="100">
        <condition>
            <expression>
                <expression>
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Server Transfer - Pull</value>
                    </item>
                    <operator name="or" />
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Server Transfer - Push</value>
                    </item>
                </expression>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="equal" />
                    <value>cd</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" class="com.tumbleweed.st.server.connectdirect.agent.ConnectDirectTransferAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.RetryAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <!-- the event exit code for which the retry agent should flag a retry to the event queue -->
                        <param-name>dontretry</param-name><param-value>"0 1 2 4 5"</param-value>
                    </param>
                    <param>
                        <param-name>internalretry</param-name><param-value>"6"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="3" executeafter="2" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.Continue">
                <params>
                    <param>
                        <param-name>continue</param-name>
                        <param-value>"0 1 2 4 5"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>

</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/PackageRetentionMaintApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: PackageRetentionMaintApp.xml,v 1.4 2006-08-05 00:46:22 flam Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="PackageRetentionMaintApp.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    <rule name="Package Retentnion Maintenance Application" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Application - Schedule</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_APPLICATION_TYPE</attribute>
                    <comparator name="equal" />
                    <value>PackageRetentionMaint</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.axway.st.server.packageretentionmaintapp.agents.PackageRetentionMaintAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>

</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/AxwayTransferCFT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: SynchronyTransfer.xml,v 1.1.2.9 2009-09-28 14:37:49 vlalov Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="AxwayTransferCFT.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    <rule name="AxwayTransferCFT" type="static" precedence="100">
        <condition>
            <expression>
                <expression>
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Server Transfer - Pull</value>
                    </item>
                    <operator name="or" />
                    <item>
                        <attribute>EventType</attribute>
                        <comparator name="equal" />
                        <value>Server Transfer - Push</value>
                    </item>
                </expression>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_SITE_PROTOCOL</attribute>
                    <comparator name="equal" />
                    <value>synchrony transfer</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" class="com.tumbleweed.st.server.synchronytransfer.agent.SynchronyTransferAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.RetryAgent">
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                    <param>
                        <!-- the event exit code for which the retry agent should flag a retry to the event queue -->
                        <param-name>dontretry</param-name><param-value>"0 1 2 4 5"</param-value>
                    </param>
                    <param>
                        <param-name>internalretry</param-name><param-value>"6"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="3" executeafter="2" streamaccess="none" class="com.tumbleweed.st.server.tm.agents.Continue">
                <params>
                    <param>
                        <param-name>continue</param-name>
                        <param-value>"0 1 2 4 5"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>
    <rule name="AxwayTransferCFTApplication" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal"/>
                    <value>Application - Incoming</value>
                </item>
                <operator name="and"/>
                <item>
                    <attribute>DXAGENT_APPLICATION_TYPE</attribute>
                    <comparator name="equal"/>
                    <value>SynchronyTransfer</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none"
                    class="com.tumbleweed.st.server.synchronytransfer.agent.SynchronyTransferAppAgent"/>
        </action>
    </rule>
    <rule name="AxwayTransferCFTReceiving" type="static" precedence="90">
        <condition>
            <item>
                <attribute>EventType</attribute>
                <comparator name="equal" />
                <value>Synchrony Transfer</value>
            </item>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.synchronytransfer.agent.SynchronyTransferReceivingAgent"/>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence" />
            <inprocess-agent id="3" executeafter="2" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.CleanupAgent" />
        </action>
    </rule>
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/SiteMailbox.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: SiteMailbox.xml,v 1.11 2006-08-05 00:46:22 flam Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="SiteMailbox.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
	<rule name="SiteMailboxApplication" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Application - Incoming</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_APPLICATION_TYPE</attribute>
                    <comparator name="equal" />
                    <value>SiteMailbox</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.mailboxapp.agents.MailboxAppAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
            <inprocess-agent id="2" executeafter="1" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.tm.agents.NextPrecedence" />
        </action>
    </rule>
	
	<rule name="SiteMailboxSubscription" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Application - Init</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_APPLICATION_TYPE</attribute>
                    <comparator name="equal" />
                    <value>SiteMailbox</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.mailboxapp.agents.MailboxSubscriptionAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
         </action>
    </rule>
	
</brpackage>

=== akbalwani/parse_server_config/data/export_configuration_55/brules/local/wptdocuments/ArchiveMaintApp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- @(#) $Id: ArchiveMaintApp.xml,v 1.1.2.1 2008-09-01 15:56:43 kmilchev Exp $ -->
<!-- Do not delete the SecureTransport VERSION line below. -->
<!-- ~VERSION~ 1 -->
<brpackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="ArchiveMaintApp.xml" version="1.0" xsi:noNamespaceSchemaLocation="businessrules.xsd">
    <rule name="Archive Maintenance Application" type="static" precedence="100">
        <condition>
            <expression>
                <item>
                    <attribute>EventType</attribute>
                    <comparator name="equal" />
                    <value>Application - Schedule</value>
                </item>
                <operator name="and" />
                <item>
                    <attribute>DXAGENT_APPLICATION_TYPE</attribute>
                    <comparator name="equal" />
                    <value>ArchiveMaint</value>
                </item>
            </expression>
        </condition>
        <action Order="yes">
            <inprocess-agent id="1" executeafter="" streamaccess="none" wait="yes" class="com.tumbleweed.st.server.archivemaintapp.agents.ArchiveMaintAgent" >
                <params>
                    <param>
                        <param-name>Impersonation</param-name>
                        <param-value>"true"</param-value>
                    </param>
                </params>
            </inprocess-agent>
        </action>
    </rule>
</brpackage>
